- name: Installing 1Password
  homebrew_cask:
    name: 1password
    state: latest
  register: install_1password_result

- name: Signing into 1Password
  shell: |
    cat <<-'EOF' | osascript -
      set changed to false

      tell application "System Events"
        tell process "1Password"
          do shell script "open -a 1Password"
          repeat while (count of windows) < 1
            delay 0.1
          end repeat

          if name of front window starts with "Welcome" then
            set value of attribute "AXEnhancedUserInterface" to true

            try
              repeat with element in (get entire contents of front window)
                if class of element is button and name of element is "Sign In" then
                  click element
                  exit repeat
                end if
              end repeat

              set found to false
              repeat while not found
                try
                  repeat with element in (get entire contents of front window)
                    if role description of element is "dialog" then
                      set found to true
                      exit repeat
                    end if
                  end repeat
                end try
              end repeat

              set prompting to false
              repeat with element in (get entire contents of front window)
                if class of element is text field then
                  set prompting to true
                  exit repeat
                end if
              end repeat

              if not prompting then
                repeat with element in (get entire contents of front window)
                  if class of element is button and name of element contains "Emergency Kit" then
                    click element
                    exit repeat
                  end if
                end repeat

                set found to false
                repeat while not found
                  try
                    repeat with element in (get entire contents of front window)
                      if class of element is button and name of element starts with "Import" then
                        set found to true
                        click element
                        exit repeat
                      end if
                    end repeat
                  end try
                end repeat

                repeat while (count of sheets of front window) < 1
                  delay 0.1
                end repeat

                keystroke "g" using {shift down, command down}
                delay 0.5

                keystroke "{{ dropbox_restore_dir }}/Applications/1Password/1Password Emergency Kit.pdf"
                keystroke return
                click button "Open" of sheet 1 of front window
              end if

              repeat while name of front window starts with "Welcome"
                delay 0.1
              end repeat

              set changed to true

              set showingDialog to true
              repeat while showingDialog
                delay 0.1
                if (count of windows) < 1 then
                  set showingDialog to false
                else
                  try
                    set found to false
                    repeat with element in (get entire contents of front window)
                      if role description of element is "dialog" then
                        set found to true
                        exit repeat
                      end if
                    end repeat
                    set showingDialog to found
                  end try
                end if
              end repeat
            on error errStr number errorNumber
              set value of attribute "AXEnhancedUserInterface" to false
              error errStr number errorNumber
            end try

            set value of attribute "AXEnhancedUserInterface" to false
          end if

          repeat while (count of windows) > 0
            repeat with element in (get entire contents of front window)
              if class of element is button and description of element contains "close" then
                click element
                exit repeat
              end if
            end repeat
          end repeat
        end tell

        tell process "coreautha"
          if window "1Password" exists
            click button "Cancel" of window "1Password"
          end if
        end tell
      end tell

      return changed
    EOF
  register: login_1password_result
  changed_when: 'login_1password_result.stdout == "true"'

- name: Setting 1Password Open Keyboard Shortcut
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "keybinds.open":'
    line: '  "keybinds.open": "Alt+Shift+CommandOrControl+[\\]\\",'
    insertafter: '^{$'
    state: present

- name: Setting 1Password Quick Access Keyboard Shortcut
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "keybinds.quickAccess":'
    line: '  "keybinds.quickAccess": "Shift+CommandOrControl+[\\]\\",'
    insertafter: '^{$'
    state: present

- name: Setting 1Password Lock Keyboard Shortcut
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "keybinds.lock":'
    line: '  "keybinds.lock": "Shift+CommandOrControl+[l]L",'
    insertafter: '^{$'
    state: present

- name: Setting 1Password Autofill Keyboard Shortcut
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "keybinds.autoFill":'
    line: '  "keybinds.autoFill": "CommandOrControl+[\\]\\",'
    insertafter: '^{$'
    state: present

- name: Setting 1Password Generator Type
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "passwordGenerator.type":'
    line: '  "passwordGenerator.type": "password-generator-menu-entry-type-random-password",'
    insertafter: '^{$'
    state: present

- name: Setting 1Password Generator Length
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "passwordGenerator.size.characters":'
    line: '  "passwordGenerator.size.characters": 20,'
    insertafter: '^{$'
    state: present

- name: Including Numbers in 1Password Generator
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "passwordGenerator.includeNumbers":'
    line: '  "passwordGenerator.includeNumbers": true,'
    insertafter: '^{$'
    state: present

- name: Including Symbols in 1Password Generator
  lineinfile:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json
    regexp: '^  "passwordGenerator.includeSymbols":'
    line: '  "passwordGenerator.includeSymbols": true,'
    insertafter: '^{$'
    state: present
