### Requires fish.yml task

- name: Installing goenv
  homebrew:
    name: goenv
    state: latest

- name: Configuring Global go Binary
  shell: |
    set -e

    existing="$(goenv version-name || true)"
    version="$(goenv install --list | grep -E '^ *[0-9]+\.[0-9]+\.[0-9]+ *$' | tail -n1 | xargs)"
    if [ "$existing" != "$version" ]; then
      goenv install --skip-existing "$version" >&2
      goenv global "$version" >&2

      echo 'changed'
    else
      echo 'current'
    fi
  register: global_go_result
  changed_when: 'global_go_result.stdout == "changed"'

- name: Installing gopls
  shell: goenv init - | source; and go install golang.org/x/tools/gopls@latest
  args:
    executable: fish
    creates: ~/.goenv/shims/gopls
