- name: Installing Homebrew
  shell: |
    set -e

    if ! type "brew" > /dev/null 2>&1; then
      echo 'installing'

      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      if [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
      elif [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
      fi
    fi

    brew doctor
  register: install_homebrew_result
  changed_when: 'install_homebrew_result.stdout_lines[0] == "installing"'

- name: Updating Homebrew and Upgrading Packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Tapping homebrew-cask-versions
  homebrew_tap:
    name: homebrew/cask-versions
